<a href="https://colab.research.google.com/github/cpython-projects/da_vn/blob/main/session_04_practice_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
from google.colab import files
uploaded = files.upload()

Saving session_04_data.csv to session_04_data (4).csv

In [106]:
import pandas as pd
df = pd.read_csv("session_04_data (2).csv", delimiter=",", encoding='utf-8')

In [107]:
df

    Unnamed: 0  ID     Name gender     Age  Salary ($)      Hire Date         Country  Weight
0            0   1    Alice      F      25     50000.0     2023-01-10             USA    70kg
1            1   2    Bob        M  Thirty     60000.0     2022-12-05          U.S.A.  154lbs
2            2   3  CHARLIE      M      40         NaN     01/15/2021              UK    65kg
3            3   4     Dave      M      22     70000.0  March 1, 2020  United Kingdom  140lbs
4            4   5      Eve      F     NaN     80000.0     2021-07-20          canada    75kg
5            5   6    Frank      M      35    120000.0     08/10/2019          Canada  165lbs
6            6   7   George      M      29         NaN     2020-05-30         Germany    80kg
7            7   8   Hannah      F      33    150000.0   July 4, 2018          France  180lbs
8            8   9    Isaac      M      45    200000.0     06-01-2017          France    90kg
9            9  10     Jack      M  Twenty    250000.0     2016-09-15          Brazil  200lbs
10          10   5      Eve      F     NaN     80000.0     2021-07-20          canada    75kg
11          11   6    Frank      M      35    120000.0     08/10/2019          Canada  165lbs

In [108]:
df.columns.tolist()

['Unnamed: 0',
 'ID',
 'Name',
 'gender',
 'Age',
 'Salary ($)',
 'Hire Date',
 'Country',
 'Weight']

In [109]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [110]:
df.columns.tolist()

['ID', 'Name', 'gender', 'Age', 'Salary ($)', 'Hire Date', 'Country', 'Weight']

In [111]:
df.rename(columns={
    'ID': 'id',
    'Name': 'user_name',
    'gender': 'gender',
    'Age': 'user_age',
    'Salary ($)': 'user_salary',
    'Hire Date': 'hire_date',
    'Country': 'country',
    'Weight': 'weight'
}, inplace=True)
df.columns.tolist()

['id',
 'user_name',
 'gender',
 'user_age',
 'user_salary',
 'hire_date',
 'country',
 'weight']

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           12 non-null     int64
 1   user_name    12 non-null     object
 2   gender       12 non-null     object
 3   user_age     10 non-null     object
 4   user_salary  10 non-null     float64
 5   hire_date    12 non-null     object
 6   country      12 non-null     object
 7   weight       12 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 900.0+ bytes

In [113]:
print("Initial shape:", df.shape)
print("\nData types:\n", df.dtypes)
print("\nMissing values:\n", df.isna().sum())

Initial shape: (12, 8)

Data types:
 id               int64
user_name       object
gender          object
user_age        object
user_salary    float64
hire_date       object
country         object
weight          object
dtype: object

Missing values:
 id             0
user_name      0
gender         0
user_age       2
user_salary    2
hire_date      0
country        0
weight         0
dtype: int64

### Handle Duplicates

**Checking for Exact Duplicates**

In [114]:
df.duplicated().sum()

np.int64(2)

In [115]:
# Identify duplicate rows
duplicates = df.duplicated()
print("Duplicate rows:\n", df[duplicates])

Duplicate rows:
     id user_name gender user_age  user_salary   hire_date country  weight
10   5       Eve      F      NaN      80000.0  2021-07-20  canada    75kg
11   6     Frank      M       35     120000.0  08/10/2019  Canada  165lbs

In [116]:
df

    id user_name gender user_age  user_salary      hire_date         country  weight
0    1     Alice      F       25      50000.0     2023-01-10             USA    70kg
1    2     Bob        M   Thirty      60000.0     2022-12-05          U.S.A.  154lbs
2    3   CHARLIE      M       40          NaN     01/15/2021              UK    65kg
3    4      Dave      M       22      70000.0  March 1, 2020  United Kingdom  140lbs
4    5       Eve      F      NaN      80000.0     2021-07-20          canada    75kg
5    6     Frank      M       35     120000.0     08/10/2019          Canada  165lbs
6    7    George      M       29          NaN     2020-05-30         Germany    80kg
7    8    Hannah      F       33     150000.0   July 4, 2018          France  180lbs
8    9     Isaac      M       45     200000.0     06-01-2017          France    90kg
9   10      Jack      M   Twenty     250000.0     2016-09-15          Brazil  200lbs
10   5       Eve      F      NaN      80000.0     2021-07-20          canada    75kg
11   6     Frank      M       35     120000.0     08/10/2019          Canada  165lbs

**df.drop_duplicates()**

In [117]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)
df

   id user_name gender user_age  user_salary      hire_date         country  weight
0   1     Alice      F       25      50000.0     2023-01-10             USA    70kg
1   2     Bob        M   Thirty      60000.0     2022-12-05          U.S.A.  154lbs
2   3   CHARLIE      M       40          NaN     01/15/2021              UK    65kg
3   4      Dave      M       22      70000.0  March 1, 2020  United Kingdom  140lbs
4   5       Eve      F      NaN      80000.0     2021-07-20          canada    75kg
5   6     Frank      M       35     120000.0     08/10/2019          Canada  165lbs
6   7    George      M       29          NaN     2020-05-30         Germany    80kg
7   8    Hannah      F       33     150000.0   July 4, 2018          France  180lbs
8   9     Isaac      M       45     200000.0     06-01-2017          France    90kg
9  10      Jack      M   Twenty     250000.0     2016-09-15          Brazil  200lbs

### Handling Incorrect Formats

**Numeric data stored as strings**

In [118]:
# Identify unique values that are not numeric
unique_ages = df.user_age.dropna().unique()
print(unique_ages)

['25' 'Thirty' '40' '22' '35' '29' '33' '45' 'Twenty']

In [119]:
# Convert non-numeric values to numbers if possible
df['user_age'] = df.user_age.replace({"Thirty": '30', "Twenty": '20'})
df.user_age.unique()

array(['25', '30', '40', '22', nan, '35', '29', '33', '45', '20'],
      dtype=object)

In [120]:
df['user_age'] = pd.to_numeric(df['user_age'], errors='coerce')
df.user_age.unique()

array([25., 30., 40., 22., nan, 35., 29., 33., 45., 20.])

**Dates stored as strings**

In [121]:
pd.to_datetime(df['hire_date'], errors='coerce')

0   2023-01-10
1   2022-12-05
2          NaT
3          NaT
4   2021-07-20
5          NaT
6   2020-05-30
7          NaT
8          NaT
9   2016-09-15
Name: hire_date, dtype: datetime64[ns]

In [122]:
from dateutil import parser

def date_parse(item):
  if pd.notna(item):
    return parser.parse(item).strftime('%Y-%m-%d')
  return item

# Приведение всех дат к ISO-формату
df['hire_date'] = df['hire_date'].apply(date_parse)
df

   id user_name gender  user_age  user_salary   hire_date         country  weight
0   1     Alice      F      25.0      50000.0  2023-01-10             USA    70kg
1   2     Bob        M      30.0      60000.0  2022-12-05          U.S.A.  154lbs
2   3   CHARLIE      M      40.0          NaN  2021-01-15              UK    65kg
3   4      Dave      M      22.0      70000.0  2020-03-01  United Kingdom  140lbs
4   5       Eve      F       NaN      80000.0  2021-07-20          canada    75kg
5   6     Frank      M      35.0     120000.0  2019-08-10          Canada  165lbs
6   7    George      M      29.0          NaN  2020-05-30         Germany    80kg
7   8    Hannah      F      33.0     150000.0  2018-07-04          France  180lbs
8   9     Isaac      M      45.0     200000.0  2017-06-01          France    90kg
9  10      Jack      M      20.0     250000.0  2016-09-15          Brazil  200lbs

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10 non-null     int64
 1   user_name    10 non-null     object
 2   gender       10 non-null     object
 3   user_age     9 non-null      float64
 4   user_salary  8 non-null      float64
 5   hire_date    10 non-null     object
 6   country      10 non-null     object
 7   weight       10 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1020.0+ bytes

In [124]:
df['hire_date'] = pd.to_datetime(df['hire_date'], format='%Y-%m-%d')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10 non-null     int64
 1   user_name    10 non-null     object
 2   gender       10 non-null     object
 3   user_age     9 non-null      float64
 4   user_salary  8 non-null      float64
 5   hire_date    10 non-null     datetime64[ns]
 6   country      10 non-null     object
 7   weight       10 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 1020.0+ bytes

**Categorical data stored as strings/numbers**

In [125]:
df['gender'] = df['gender'].astype('category')

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10 non-null     int64
 1   user_name    10 non-null     object
 2   gender       10 non-null     category
 3   user_age     9 non-null      float64
 4   user_salary  8 non-null      float64
 5   hire_date    10 non-null     datetime64[ns]
 6   country      10 non-null     object
 7   weight       10 non-null     object
dtypes: category(1), datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 1.0+ KB

### Handling Common Inconsistencies

**Text: Mixed cases and extra spaces**

In [127]:
# Clean customer names
df['user_name'] = df['user_name'].str.strip().str.title()

**Units: Inconsistent measurements**

In [128]:
def convert_weight(x):
    if not isinstance(x, str):
        return x

    if 'kg' in x:
        return float(x.replace('kg', ''))
    if 'lbs' in x:
        return float(x.replace('lbs', '')) * 0.453592

df['weight_kg'] = df['weight'].apply(convert_weight)
df.drop('weight', axis=1, inplace=True)
df

   id user_name gender  user_age  user_salary  hire_date         country  weight_kg
0   1     Alice      F      25.0      50000.0 2023-01-10             USA  70.000000
1   2       Bob      M      30.0      60000.0 2022-12-05          U.S.A.  69.853168
2   3   Charlie      M      40.0          NaN 2021-01-15              UK  65.000000
3   4      Dave      M      22.0      70000.0 2020-03-01  United Kingdom  63.502880
4   5       Eve      F       NaN      80000.0 2021-07-20          canada  75.000000
5   6     Frank      M      35.0     120000.0 2019-08-10          Canada  74.842680
6   7    George      M      29.0          NaN 2020-05-30         Germany  80.000000
7   8    Hannah      F      33.0     150000.0 2018-07-04          France  81.646560
8   9     Isaac      M      45.0     200000.0 2017-06-01          France  90.000000
9  10      Jack      M      20.0     250000.0 2016-09-15          Brazil  90.718400

**Categories: Different spellings**

In [129]:
df.country.unique()

array(['USA', 'U.S.A.', 'UK', 'United Kingdom', 'canada', 'Canada',
       'Germany', 'France', 'Brazil'], dtype=object)

In [130]:
# Standardize country names
country_mapping = {
    'USA': 'United States',
    'U.S.A.': 'United States',
    'UK': 'United Kingdom',
    'canada': 'Canada'
}
df['country'] = df['country'].replace(country_mapping).str.title()

### Handling Missing Values

**df.dropna()**

In [131]:
# Drop rows with any missing values
df_dropped_rows = df.dropna()
df_dropped_rows

   id user_name gender  user_age  user_salary  hire_date         country  weight_kg
0   1     Alice      F      25.0      50000.0 2023-01-10   United States  70.000000
1   2       Bob      M      30.0      60000.0 2022-12-05   United States  69.853168
3   4      Dave      M      22.0      70000.0 2020-03-01  United Kingdom  63.502880
5   6     Frank      M      35.0     120000.0 2019-08-10          Canada  74.842680
7   8    Hannah      F      33.0     150000.0 2018-07-04          France  81.646560
8   9     Isaac      M      45.0     200000.0 2017-06-01          France  90.000000
9  10      Jack      M      20.0     250000.0 2016-09-15          Brazil  90.718400

**df.dropna(axis=1)**

In [132]:
# Drop columns with any missing values
df_dropped_cols = df.dropna(axis=1)
df_dropped_cols

   id user_name gender  hire_date         country  weight_kg
0   1     Alice      F 2023-01-10   United States  70.000000
1   2       Bob      M 2022-12-05   United States  69.853168
2   3   Charlie      M 2021-01-15  United Kingdom  65.000000
3   4      Dave      M 2020-03-01  United Kingdom  63.502880
4   5       Eve      F 2021-07-20          Canada  75.000000
5   6     Frank      M 2019-08-10          Canada  74.842680
6   7    George      M 2020-05-30         Germany  80.000000
7   8    Hannah      F 2018-07-04          France  81.646560
8   9     Isaac      M 2017-06-01          France  90.000000
9  10      Jack      M 2016-09-15          Brazil  90.718400

**df.fillna(0)**

In [134]:
# Fill missing numeric values with 0
df_filled_zero = df['user_salary'].fillna(0)
df_filled_zero

0     50000.0
1     60000.0
2         0.0
3     70000.0
4     80000.0
5    120000.0
6         0.0
7    150000.0
8    200000.0
9    250000.0
Name: user_salary, dtype: float64

**df.fillna(df.mean())**

In [135]:
# Fill missing numeric values with column mean
df_filled_mean = df.fillna(df.mean(numeric_only=True))
df_filled_mean

   id user_name gender  user_age  user_salary  hire_date         country  weight_kg
0   1     Alice      F      25.0      50000.0 2023-01-10   United States  70.000000
1   2       Bob      M      30.0      60000.0 2022-12-05   United States  69.853168
2   3   Charlie      M      40.0     122500.0 2021-01-15  United Kingdom  65.000000
3   4      Dave      M      22.0      70000.0 2020-03-01  United Kingdom  63.502880
4   5       Eve      F      31.0      80000.0 2021-07-20          Canada  75.000000
5   6     Frank      M      35.0     120000.0 2019-08-10          Canada  74.842680
6   7    George      M      29.0     122500.0 2020-05-30         Germany  80.000000
7   8    Hannah      F      33.0     150000.0 2018-07-04          France  81.646560
8   9     Isaac      M      45.0     200000.0 2017-06-01          France  90.000000
9  10      Jack      M      20.0     250000.0 2016-09-15          Brazil  90.718400

**df.fillna(df.median())**

In [136]:
# Fill missing numeric values with column median
df_filled_median = df.fillna(df.median(numeric_only=True))
df_filled_median

   id user_name gender  user_age  user_salary  hire_date         country  weight_kg
0   1     Alice      F      25.0      50000.0 2023-01-10   United States  70.000000
1   2       Bob      M      30.0      60000.0 2022-12-05   United States  69.853168
2   3   Charlie      M      40.0     100000.0 2021-01-15  United Kingdom  65.000000
3   4      Dave      M      22.0      70000.0 2020-03-01  United Kingdom  63.502880
4   5       Eve      F      30.0      80000.0 2021-07-20          Canada  75.000000
5   6     Frank      M      35.0     120000.0 2019-08-10          Canada  74.842680
6   7    George      M      29.0     100000.0 2020-05-30         Germany  80.000000
7   8    Hannah      F      33.0     150000.0 2018-07-04          France  81.646560
8   9     Isaac      M      45.0     200000.0 2017-06-01          France  90.000000
9  10      Jack      M      20.0     250000.0 2016-09-15          Brazil  90.718400

**df.fillna(method='ffill')**

In [137]:
# Forward fill missing values
df_ffill = df.fillna(method='ffill')
df_ffill

<ipython-input-137-bc39a2d051c3>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')

   id user_name gender  user_age  user_salary  hire_date         country  weight_kg
0   1     Alice      F      25.0      50000.0 2023-01-10   United States  70.000000
1   2       Bob      M      30.0      60000.0 2022-12-05   United States  69.853168
2   3   Charlie      M      40.0      60000.0 2021-01-15  United Kingdom  65.000000
3   4      Dave      M      22.0      70000.0 2020-03-01  United Kingdom  63.502880
4   5       Eve      F      22.0      80000.0 2021-07-20          Canada  75.000000
5   6     Frank      M      35.0     120000.0 2019-08-10          Canada  74.842680
6   7    George      M      29.0     120000.0 2020-05-30         Germany  80.000000
7   8    Hannah      F      33.0     150000.0 2018-07-04          France  81.646560
8   9     Isaac      M      45.0     200000.0 2017-06-01          France  90.000000
9  10      Jack      M      20.0     250000.0 2016-09-15          Brazil  90.718400

**df.fillna(method='bfill')**

In [138]:
# Backward fill missing values
df_bfill = df.fillna(method='bfill')
df_bfill

<ipython-input-138-3b638ae5ba2b>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method='bfill')

   id user_name gender  user_age  user_salary  hire_date         country  weight_kg
0   1     Alice      F      25.0      50000.0 2023-01-10   United States  70.000000
1   2       Bob      M      30.0      60000.0 2022-12-05   United States  69.853168
2   3   Charlie      M      40.0      70000.0 2021-01-15  United Kingdom  65.000000
3   4      Dave      M      22.0      70000.0 2020-03-01  United Kingdom  63.502880
4   5       Eve      F      35.0      80000.0 2021-07-20          Canada  75.000000
5   6     Frank      M      35.0     120000.0 2019-08-10          Canada  74.842680
6   7    George      M      29.0     150000.0 2020-05-30         Germany  80.000000
7   8    Hannah      F      33.0     150000.0 2018-07-04          France  81.646560
8   9     Isaac      M      45.0     200000.0 2017-06-01          France  90.000000
9  10      Jack      M      20.0     250000.0 2016-09-15          Brazil  90.718400

**df.interpolate()**

In [140]:
# Interpolate missing values
df_interpolated = df.user_salary.interpolate()
df_interpolated

0     50000.0
1     60000.0
2     65000.0
3     70000.0
4     80000.0
5    120000.0
6    135000.0
7    150000.0
8    200000.0
9    250000.0
Name: user_salary, dtype: float64

**Fill df**

In [141]:
age_median = df['user_age'].median()
df['user_age'] = df['user_age'].fillna(age_median)
salary_median = df['user_salary'].median()
df['user_salary'] = df['user_salary'].fillna(salary_median)

df

   id user_name gender  user_age  user_salary  hire_date         country  weight_kg
0   1     Alice      F      25.0      50000.0 2023-01-10   United States  70.000000
1   2       Bob      M      30.0      60000.0 2022-12-05   United States  69.853168
2   3   Charlie      M      40.0     100000.0 2021-01-15  United Kingdom  65.000000
3   4      Dave      M      22.0      70000.0 2020-03-01  United Kingdom  63.502880
4   5       Eve      F      30.0      80000.0 2021-07-20          Canada  75.000000
5   6     Frank      M      35.0     120000.0 2019-08-10          Canada  74.842680
6   7    George      M      29.0     100000.0 2020-05-30         Germany  80.000000
7   8    Hannah      F      33.0     150000.0 2018-07-04          France  81.646560
8   9     Isaac      M      45.0     200000.0 2017-06-01          France  90.000000
9  10      Jack      M      20.0     250000.0 2016-09-15          Brazil  90.718400

### Handling Outliers

**Detecting outliers using Interquartile Range (IQR)**

In [142]:
Q1 = df.user_salary.quantile(0.25)
Q3 = df.user_salary.quantile(0.75)
IQR = Q3 - Q1
outliers = df[(df["user_salary"] < (Q1 - 1.5 * IQR)) | (df["user_salary"] > (Q3 + 1.5 * IQR))]
outliers

   id user_name gender  user_age  user_salary  hire_date country  weight_kg
9  10      Jack      M      20.0     250000.0 2016-09-15  Brazil    90.7184

In [143]:
# Removing outliers
filtered_df = df[~df.index.isin(outliers.index)]

### Identifying the Highest-Paid Employees by Country

In [144]:
top_salaries = filtered_df.groupby(df.country)["user_salary"].max()
print(top_salaries)

country
Canada            120000.0
France            200000.0
Germany           100000.0
United Kingdom    100000.0
United States      60000.0
Name: user_salary, dtype: float64

### Calculating Average Age of Employees

In [145]:
print(df.user_age.mean())

30.9